
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 87
#define YY_END_OF_BUFFER 88
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[239] =
    {   0,
       86,   86,   88,   86,    6,    1,   71,   86,   86,   77,
       70,   86,   11,   12,   75,   74,    8,   73,   16,   76,
       86,   86,   15,    7,   54,   79,   56,   85,   13,   14,
       61,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,    9,   78,   10,
       72,   58,    0,    0,    0,    0,    0,   64,   59,   67,
        0,   62,   51,   65,   52,   66,    0,    0,    0,    4,
       63,   83,    0,    0,    0,   14,   13,   50,   53,   57,
       55,   49,   85,   82,   85,    0,   68,   85,   85,   85,
       85,   85,   85,   22,   85,   85,   85,   85,   85,   85,

       24,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   69,   60,   80,    0,    0,    0,   46,   84,
        0,    0,    0,    4,   48,   47,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   23,   85,   25,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,    0,    0,   81,    0,    0,    5,   45,   85,
       37,   17,   85,   85,   85,   85,   19,   42,   85,   85,
       39,   26,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   34,   85,    0,    0,   35,   44,   85,   85,   85,
       85,   20,   85,   28,   85,   85,   85,   85,   85,   32,

       85,   21,    0,    0,   85,   85,   18,   43,   27,   29,
       30,   31,   36,   85,   85,    0,    0,   85,   38,   41,
       85,    0,    0,    0,   40,   33,    0,    0,    0,    0,
        0,    3,    2,    0,    0,    0,    0,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,    1,    1,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       28,    1,   29,   30,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   27,   41,   42,   43,   44,
       45,   46,   27,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   56,   57,   58,   59,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[60] =
    {   0,
        1,    2,    3,    1,    4,    5,    6,    1,    5,    5,
        1,    1,    5,    5,    5,    5,    5,    7,    2,    8,
        8,    9,    5,   10,   11,    2,   12,   13,    9,    5,
       14,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,    1,   15,    9,    5
    } ;

static const flex_int16_t yy_base[253] =
    {   0,
        0,    0,  275,  973,  973,  973,  246,  262,   55,  239,
       51,    0,  973,  973,  234,   48,  973,   47,   47,   52,
       60,   64,  227,  973,   64,  222,   44,   63,  973,  973,
      210,    0,   65,   69,   73,   74,   89,   93,  104,  102,
      108,  109,  118,  120,  118,  134,  136,  973,   99,  973,
      973,  973,  217,  169,  173,  187,  171,  973,  973,  973,
      198,  973,  973,  973,  973,  973,  185,   54,   95,    0,
      973,  973,   82,  166,  170,  973,  973,  174,  973,  973,
      973,  152,  157,  973,    0,   83,  973,  161,  162,  172,
      173,  172,  185,  186,  189,  190,  202,  209,  213,  217,

      218,  229,  223,  228,  241,  250,  251,  252,  255,  267,
      271,  281,  973,   89,  154,  114,  103,  301,  973,  973,
      305,  324,  326,    0,  973,  973,  286,  302,  303,  304,
      305,  320,  323,  325,  328,  340,  342,  343,  345,  354,
      357,  359,  368,  350,  370,  366,  376,  386,  392,  395,
      406,  400,   89,   81,  973,  429,  443,  973,  406,  414,
      410,  418,  424,  430,  434,  437,  438,  444,  451,  450,
      458,  463,  466,  473,  470,  486,  495,  496,  504,  500,
      508,  503,  515,   63,   42,  516,  520,  521,  528,  535,
      534,  538,  541,  542,  554,  555,  560,  561,  578,  573,

      577,  578,   51,   48,  582,  585,  595,  598,  599,  602,
      603,  615,  616,  628,  631,  190,   43,  635,  632,  636,
      648,  214,  686,  159,  652,  655,  444,  707,  280,  373,
      713,  973,  973,  731,  739,  749,  758,  973,  815,  157,
      829,  837,  845,  852,  866,  881,  896,  911,  923,  932,
      943,  957
    } ;

static const flex_int16_t yy_def[253] =
    {   0,
      238,    1,  238,  238,  238,  238,  238,  239,  238,  238,
      238,  240,  238,  238,  238,  238,  238,  238,  238,  238,
      241,  241,  238,  238,  238,  238,  238,  242,  238,  238,
      238,  243,  242,  242,  242,   35,   35,   35,   35,   37,
       35,   35,   35,   35,   37,   35,   35,  238,  244,  238,
      238,  238,  239,  239,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  245,  246,  247,
      238,  238,  238,  238,  241,  238,  238,  238,  238,  238,
      238,  238,   35,  238,  243,  244,  238,   35,   35,   35,
       35,   37,   37,   37,   37,   37,   37,   35,   35,   35,

       35,   35,   37,   37,   35,   35,   35,   35,   35,   35,
       35,   35,  238,  244,  239,  238,  238,  238,  238,  238,
      246,  246,  248,  247,  238,  238,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   37,   37,   37,   37,   37,   35,   35,
       35,   37,  238,  238,  238,  246,  246,  238,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   35,   35,   35,   35,   37,
       37,   37,   37,  238,  238,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   35,   35,   35,

       37,   37,  238,  238,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,  249,  238,   37,   37,   37,
       37,  249,  249,  250,   37,   37,  238,  238,  250,  250,
      251,  238,  238,  252,  238,  251,  252,    0,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238
    } ;

static const flex_int16_t yy_nxt[1033] =
    {   0,
        4,    5,    6,    4,    5,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   28,   40,
       28,   41,   28,   28,   28,   28,   42,   43,   44,   45,
       46,   47,   28,   28,   28,   48,   49,   50,   51,   55,
       59,   55,   63,   65,   67,   69,   68,   68,   81,   82,
       70,   66,   64,   68,   68,   60,   71,   73,  224,   74,
       74,   73,  217,   75,   75,   77,  216,   78,   79,   56,
       84,  204,   84,   85,   57,   85,   84,  122,  122,   85,

       84,   68,   68,   85,   90,   83,  203,  238,  123,   93,
       84,   91,   83,  238,   88,   89,   84,   92,   94,   86,
       83,   86,  185,  113,   83,   86,   84,   83,  184,   86,
       95,   83,   96,   83,   98,   83,  154,   99,  101,   83,
       83,   97,   83,   83,  104,  102,   83,   83,  100,   83,
      153,   83,  103,   83,   83,  114,  105,  106,   83,   83,
       54,  110,   83,  229,   83,   83,  107,   83,   61,  108,
       83,   61,   83,  109,  112,   54,  126,   55,  111,   55,
       83,  115,  230,   73,  115,   74,   74,   73,   83,   75,
       75,  115,   83,   83,  222,   83,  222,  128,  125,   83,

       83,   83,  119,   83,  130,   83,   83,   56,  118,  127,
       83,   83,   57,   83,  117,  131,   83,   83,  222,  129,
      222,  132,  116,   54,   83,  115,   83,   83,   83,   83,
       83,   83,   83,   83,   87,  133,  134,   83,   83,  135,
       83,   83,   83,   83,   83,   83,   80,   83,   83,   83,
      136,   83,   76,  137,   83,   83,   83,   83,   62,  138,
       83,   83,   83,   58,   83,  139,  141,   83,   54,   83,
       52,   83,   83,   83,  238,   83,  142,  140,  238,   83,
       83,   83,   83,   83,  229,  143,   83,  144,   83,   83,
       83,  147,  238,   83,   83,   83,   83,  146,   83,   83,

      148,  238,   83,  230,  145,   83,  149,  122,  122,   83,
      151,   83,   83,  155,  150,   83,  155,   83,  123,   83,
      152,  238,  155,  155,   83,   83,  122,  122,  157,  157,
      159,  238,  238,  160,   83,   83,   83,  123,  161,  123,
       83,   83,   83,   83,  158,  238,   83,   83,   83,   83,
      162,  165,  163,  164,   83,  166,   83,  155,   83,   83,
      167,   83,  238,   83,   83,  238,   83,   83,  238,   83,
      168,   83,   83,  170,   83,  169,   83,  238,   83,  238,
       83,   83,  238,   83,   83,   83,   83,   83,   83,  171,
       83,   83,   83,  175,  172,   83,  238,   83,   83,   83,

      238,   83,   83,   83,  238,  176,   83,   83,  173,   83,
      238,   83,   83,   83,  174,  177,  238,   83,   83,   83,
      238,  179,   83,   83,  178,  238,   83,   83,   83,   83,
       83,  122,  122,   83,  181,  238,  180,   83,   83,   83,
      182,  183,  123,   83,   83,  122,  122,   83,  227,   83,
       83,   83,   83,   83,  186,   83,  123,   83,   83,   83,
      238,   83,   83,  228,  228,   83,   83,   83,  238,  188,
       83,   83,  187,   83,  238,   83,   83,   83,  190,   83,
       83,   83,   83,  189,  238,   83,   83,   83,  238,   83,
       83,   83,   83,   83,   83,  238,   83,  191,  192,   83,

      238,   83,   83,   83,   83,  195,   83,   83,  238,   83,
       83,   83,  193,   83,   83,   83,   83,   83,   83,  238,
      238,  194,   83,  238,   83,   83,   83,   83,  197,  198,
      196,  238,  238,   83,   83,   83,  238,  238,  199,   83,
       83,   83,   83,  200,   83,  201,   83,  238,   83,   83,
      202,   83,   83,  238,  238,   83,   83,   83,   83,   83,
       83,   83,   83,   83,  205,  238,  238,   83,   83,  206,
      207,   83,   83,   83,  238,   83,   83,  208,   83,   83,
       83,   83,   83,   83,  209,   83,   83,   83,  210,  238,
       83,  211,   83,   83,   83,   83,   83,   83,   83,  213,

      238,   83,  238,   83,   83,   83,   83,   83,  212,   83,
      238,   83,   83,  214,  238,  238,   83,   83,   83,   83,
      215,   83,   83,   83,  238,   83,   83,  238,   83,   83,
       83,  218,  238,  219,   83,  238,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,  238,  238,
       83,   83,  238,  238,   83,   83,   83,   83,   83,   83,
      238,  238,  238,  238,  220,  238,  221,   83,   83,   83,
      225,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,  238,  226,   83,   83,  238,  238,   83,   83,   83,
      227,   83,  238,   83,  238,   83,   83,  238,   83,  238,

       83,  238,  238,  238,   83,  228,  228,   83,  232,  232,
      238,  232,  238,  232,  233,  233,  238,  233,  238,  233,
      238,  238,  238,  238,  238,  232,  228,  228,  238,  238,
      234,  233,  233,  233,  238,  233,  238,  233,  235,  238,
      233,  233,  238,  233,  238,  233,  238,  238,  238,  233,
      233,  233,  238,  233,  238,  233,  235,  233,  238,  233,
      233,  238,  233,  232,  233,  238,  234,  233,  238,  233,
      238,  238,  238,  238,  235,  238,  233,  238,  238,  238,
      238,  238,  238,  235,  238,  238,  238,  233,  238,  238,
      238,  238,  238,  238,  238,  233,  238,  238,  238,  238,

      238,  238,  238,  238,  238,  233,  238,  238,  238,  238,
      238,  238,  238,  238,  233,   53,   53,  238,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
      238,  238,  238,   72,   83,  238,  238,  238,   83,   83,
       83,   83,   85,  238,  238,  238,   85,  238,   85,   86,
      238,  238,   86,   86,   86,  238,   86,  120,  120,  120,
      120,  120,  238,  120,  238,  120,  120,  238,  238,  238,
      120,  121,  121,  121,  121,  121,  121,  121,  121,  121,
      121,  121,  121,  121,  121,  121,  124,  124,  238,  124,

      124,  124,  124,  124,  124,  124,  124,  124,  124,  124,
      124,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  223,  238,  223,  238,
      238,  238,  238,  238,  223,  231,  238,  238,  238,  238,
      238,  231,  238,  231,  236,  236,  236,  238,  236,  236,
      238,  238,  238,  238,  236,  238,  238,  236,  237,  237,
      237,  238,  237,  238,  238,  238,  238,  238,  237,  238,
      238,  237,    3,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,

      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238
    } ;

static const flex_int16_t yy_chk[1033] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    9,
       11,    9,   16,   18,   19,   20,   19,   19,   27,   27,
       20,   18,   16,   68,   68,   11,   20,   21,  217,   21,
       21,   22,  204,   22,   22,   25,  203,   25,   25,    9,
       28,  185,   33,   28,    9,   33,   34,   69,   69,   34,

       35,   73,   73,   35,   35,   36,  184,   86,   69,   36,
       86,   35,   36,  114,   33,   34,  114,   35,   36,   28,
       37,   33,  154,   49,   38,   34,   49,   37,  153,   35,
       37,   38,   37,   37,   38,   39,  117,   38,   40,   41,
       42,   37,   39,   40,   42,   40,   41,   42,   39,   43,
      116,   44,   41,   42,   40,   49,   43,   43,   44,   45,
      115,   45,   43,  224,   44,   46,   43,   47,  240,   43,
       45,  240,   46,   44,   47,   54,   82,   55,   46,   55,
       47,   54,  224,   74,   54,   74,   74,   75,   83,   75,
       75,   54,   88,   89,  216,   83,  216,   89,   78,   88,

       89,   83,   67,   90,   91,   88,   89,   55,   61,   88,
       90,   91,   55,   92,   57,   92,   90,   91,  222,   90,
      222,   93,   56,   53,   92,   54,   93,   94,   93,   94,
       95,   96,   95,   96,   31,   94,   95,   93,   94,   96,
       98,   95,   96,   97,   99,   97,   26,   98,  100,  101,
       97,   99,   23,   98,   97,  100,  101,   99,   15,   99,
      102,  100,  101,   10,  103,  100,  103,  102,    8,  104,
        7,  104,  105,  102,    3,  103,  104,  102,    0,  105,
      104,  106,  107,  108,  229,  105,  109,  106,  106,  107,
      108,  108,    0,  109,  106,  107,  108,  107,  110,  109,

      109,    0,  111,  229,  106,  110,  110,  121,  121,  111,
      111,  110,  112,  118,  110,  111,  118,  127,  121,  112,
      112,    0,  118,  118,  127,  112,  122,  122,  123,  123,
      127,    0,    0,  128,  129,  130,  131,  122,  129,  123,
      128,  129,  130,  131,  123,    0,  128,  129,  130,  131,
      130,  132,  131,  131,  133,  133,  134,  118,  132,  135,
      134,  133,    0,  134,  132,    0,  135,  133,    0,  134,
      135,  136,  135,  137,  138,  136,  139,  230,  136,    0,
      137,  138,    0,  139,  136,  140,  137,  138,  141,  139,
      142,  144,  140,  144,  141,  141,  230,  142,  140,  143,

        0,  141,  144,  142,    0,  145,  143,  146,  142,  146,
        0,  145,  143,  145,  143,  146,    0,  147,  146,  147,
        0,  148,  145,  149,  147,    0,  150,  148,  147,  148,
      149,  156,  156,  150,  150,    0,  149,  151,  148,  150,
      151,  152,  156,  152,  151,  157,  157,  159,  227,  159,
      151,  161,  152,  161,  160,  160,  157,  160,  159,  162,
        0,  162,  161,  227,  227,  163,  160,  163,    0,  164,
      162,  164,  163,  164,    0,  165,  163,  165,  166,  167,
      166,  167,  164,  165,    0,  168,  165,  168,    0,  166,
      167,  170,  169,  170,  169,    0,  168,  169,  170,  171,

        0,  171,  170,  169,  172,  175,  172,  173,    0,  173,
      171,  175,  173,  175,  174,  172,  174,  176,  173,    0,
        0,  174,  175,    0,  176,  174,  177,  178,  177,  178,
      176,    0,    0,  177,  178,  179,    0,    0,  179,  177,
      178,  180,  179,  180,  182,  181,  182,    0,  179,  181,
      183,  181,  180,    0,    0,  182,  183,  186,  183,  186,
      181,  187,  188,  187,  188,    0,    0,  183,  186,  189,
      190,  189,  187,  188,    0,  191,  190,  191,  190,  192,
      189,  192,  193,  194,  193,  194,  191,  190,  195,    0,
      192,  196,  198,  193,  194,  195,  196,  195,  196,  198,

        0,  197,    0,  197,  200,  198,  195,  196,  197,  199,
        0,  200,  197,  199,    0,    0,  199,  200,  201,  202,
      201,  202,  199,  205,    0,  205,  206,    0,  206,  201,
      202,  205,    0,  206,  205,    0,  207,  206,  207,  208,
      209,  208,  209,  210,  211,  210,  211,  207,    0,    0,
      208,  209,    0,    0,  210,  211,  212,  213,  212,  213,
        0,    0,    0,    0,  214,    0,  215,  212,  213,  214,
      218,  214,  215,  219,  215,  219,  218,  220,  218,  220,
      214,    0,  221,  215,  219,    0,    0,  218,  220,  221,
      223,  221,  223,  225,    0,  225,  226,    0,  226,    0,

      221,    0,    0,    0,  225,  223,  223,  226,  228,  228,
        0,  228,    0,  228,  231,  231,    0,  231,    0,  231,
        0,    0,    0,    0,    0,  228,  228,  228,    0,    0,
      231,  231,  234,  234,    0,  234,    0,  234,  231,    0,
      235,  235,    0,  235,    0,  235,    0,    0,    0,  234,
      236,  236,    0,  236,    0,  236,  234,  235,    0,  237,
      237,    0,  237,  228,  237,    0,  236,  236,    0,  231,
        0,    0,    0,    0,  236,    0,  237,    0,    0,    0,
        0,    0,    0,  237,    0,    0,    0,  234,    0,    0,
        0,    0,    0,    0,    0,  235,    0,    0,    0,    0,

        0,    0,    0,    0,    0,  236,    0,    0,    0,    0,
        0,    0,    0,    0,  237,  239,  239,    0,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
        0,    0,    0,  241,  242,    0,    0,    0,  242,  242,
      242,  242,  243,    0,    0,    0,  243,    0,  243,  244,
        0,    0,  244,  244,  244,    0,  244,  245,  245,  245,
      245,  245,    0,  245,    0,  245,  245,    0,    0,    0,
      245,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  247,  247,    0,  247,

      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  249,    0,  249,    0,
        0,    0,    0,    0,  249,  250,    0,    0,    0,    0,
        0,  250,    0,  250,  251,  251,  251,    0,  251,  251,
        0,    0,    0,    0,  251,    0,    0,  251,  252,  252,
      252,    0,  252,    0,    0,    0,    0,    0,  252,    0,
        0,  252,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,

      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 2 "lex.l"
	#include <stdio.h>
	#include <string.h>
	#include "y.tab.h"
	int yylineno;
	#define ANSI_COLOR_RED		"\x1b[31m"
	#define ANSI_COLOR_GREEN	"\x1b[32m"
	#define ANSI_COLOR_YELLOW	"\x1b[33m"
	#define ANSI_COLOR_BLUE		"\x1b[34m"
	#define ANSI_COLOR_MAGENTA	"\x1b[35m"
	#define ANSI_COLOR_CYAN		"\x1b[36m"
	#define ANSI_COLOR_RESET	"\x1b[0m"

	struct symboltable
	{
		char name[100];
		char class[100];
		char type[100];
		char value[100];
		int nestval;
		int lineno;
		int length;
		int params_count;
	}ST[1001];

	struct constanttable
	{
		char name[100];
		char type[100];
		int length;
	}CT[1001];

	int currnest = 0;
	int params_count = 0;
	extern int yylval;

	int hash(char *str)
	{
		int value = 0;
		for(int i = 0 ; i < strlen(str) ; i++)
		{
			value = 10*value + (str[i] - 'A');
			value = value % 1001;
			while(value < 0)
				value = value + 1001;
		}
		return value;
	}

	int lookupST(char *str)
	{
		int value = hash(str);
		if(ST[value].length == 0)
		{
			return 0;
		}
		else if(strcmp(ST[value].name,str)==0)
		{
			
			return value;
		}
		else
		{
			for(int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,str)==0)
				{
					
					return i;
				}
			}
			return 0;
		}
	}

	int lookupCT(char *str)
	{
		int value = hash(str);
		if(CT[value].length == 0)
			return 0;
		else if(strcmp(CT[value].name,str)==0)
			return 1;
		else
		{
			for(int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(CT[i].name,str)==0)
				{
					return 1;
				}
			}
			return 0;
		}
	}

	void insertSTline(char *str1, int line)
	{
		for(int i = 0 ; i < 1001 ; i++)
		{
			if(strcmp(ST[i].name,str1)==0)
			{
				ST[i].lineno = line;
			}
		}
	}


	void insertST(char *str1, char *str2)
	{
		if(lookupST(str1))
		{
			if(strcmp(ST[lookupST(str1)].class,"Identifier")==0 && strcmp(str2,"Array Identifier")==0)
			{
				printf("Error use of array\n");
				exit(0);
			}	
			return;
		}
		else
		{
			int value = hash(str1);
			if(ST[value].length == 0)
			{
				strcpy(ST[value].name,str1);
				strcpy(ST[value].class,str2);
				ST[value].length = strlen(str1);
				ST[value].nestval = 9999;
				ST[value].params_count = -1;
				insertSTline(str1,yylineno);
				return;
			}

			int pos = 0;

			for (int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(ST[i].length == 0)
				{
					pos = i;
					break;
				}
			}

			strcpy(ST[pos].name,str1);
			strcpy(ST[pos].class,str2);
			ST[pos].length = strlen(str1);
			ST[pos].nestval = 9999;
			ST[pos].params_count = -1;
		}
	}

	void insertSTtype(char *str1, char *str2)
	{
		for(int i = 0 ; i < 1001 ; i++)
		{
			if(strcmp(ST[i].name,str1)==0)
			{
				strcpy(ST[i].type,str2);
			}
		}
    }

	void insertSTvalue(char *str1, char *str2)
	{
		for(int i = 0 ; i < 1001 ; i++)
		{
			if(strcmp(ST[i].name,str1)==0 && ST[i].nestval == currnest)
			{
				strcpy(ST[i].value,str2);
			}
		}
	}


	void insertSTnest(char *s, int nest)
	{
		if(lookupST(s) && ST[lookupST(s)].nestval != 9999)
		{
             int pos = 0;
             int value = hash(s);
			for (int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(ST[i].length == 0)
				{
					pos = i;
					break;
				}
			}

			strcpy(ST[pos].name,s);
			strcpy(ST[pos].class,"Identifier");
			ST[pos].length = strlen(s);
			ST[pos].nestval = nest;
			ST[pos].params_count = -1;
			ST[pos].lineno = yylineno;
		}
		else
		{
			for(int i = 0 ; i < 1001 ; i++)
			{
				if(strcmp(ST[i].name,s)==0 )
				{
					ST[i].nestval = nest;
				}
			}
		}
	}

	void insertSTparamscount(char *s, int count)
	{
		for(int i = 0 ; i < 1001 ; i++)
		{
			if(strcmp(ST[i].name,s)==0 )
			{
				ST[i].params_count = count;
			}
		}
	}

	int getSTparamscount(char *s)
	{
		for(int i = 0 ; i < 1001 ; i++)
		{
			if(strcmp(ST[i].name,s)==0 )
			{
				return ST[i].params_count;
			}
		}
		return -2;
	}

	void insertSTF(char *s)
	{
		for(int i = 0 ; i < 1001 ; i++)
		{
			if(strcmp(ST[i].name,s)==0 )
			{
				strcpy(ST[i].class,"Function");
				return;
			}
		}

	}

	void insertCT(char *str1, char *str2)
	{
		if(lookupCT(str1))
			return;
		else
		{
			int value = hash(str1);
			if(CT[value].length == 0)
			{
				strcpy(CT[value].name,str1);
				strcpy(CT[value].type,str2);
				CT[value].length = strlen(str1);
				return;
			}

			int pos = 0;

			for (int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(CT[i].length == 0)
				{
					pos = i;
					break;
				}
			}

			strcpy(CT[pos].name,str1);
			strcpy(CT[pos].type,str2);
			CT[pos].length = strlen(str1);
		}
	}

	void deletedata (int nesting)
	{
		for(int i = 0 ; i < 1001 ; i++)
		{
			if(ST[i].nestval == nesting)
			{
				ST[i].nestval = 99999;
			}
		}


	}

	int checkscope(char *s)
	{
		int flag = 0;
		for(int i = 0 ; i < 1000 ; i++)
		{
			if(strcmp(ST[i].name,s)==0)
			{
				if(ST[i].nestval > currnest)
				{
					flag = 1;
				}
				else
				{
					flag = 0;
					break;
				}
			}
		}
		if(!flag)
		{
			return 1;
		}
		else
		{
			return 0;
		}
	}

	int check_id_is_func(char *s)
	{
		for(int i = 0 ; i < 1000 ; i++)
		{
			if(strcmp(ST[i].name,s)==0)
			{
				if(strcmp(ST[i].class,"Function")==0)
					return 1;
			}
		}
		return 0;
	}

	int checkarray(char *s)
	{
		for(int i = 0 ; i < 1000 ; i++)
		{
			if(strcmp(ST[i].name,s)==0)
			{
				if(strcmp(ST[i].class,"Array Identifier")==0)
				{
					return 0;
				}
			}
		}
		return 1;
	}

	int duplicate(char *s)
	{
		for(int i = 0 ; i < 1000 ; i++)
		{
			if(strcmp(ST[i].name,s)==0)
			{				
				if(ST[i].nestval == currnest)
				{
			        return 1;
				}
			}
		}
		
		return 0;
	}

	int check_duplicate(char* str)
	{
		for(int i=0; i<1001; i++)
		{
			if(strcmp(ST[i].name, str) == 0 && strcmp(ST[i].class, "Function") == 0)
			{
				printf("Function redeclaration not allowed\n");
				exit(0);
			}
		}
	}

	int check_declaration(char* str, char *check_type)
	{
		for(int i=0; i<1001; i++)
		{
			if(strcmp(ST[i].name, str) == 0 && strcmp(ST[i].class, "Function") == 0 || strcmp(ST[i].name,"printf")==0 )
			{
				return 1;
			}
		}
		return 0;
	}

	int check_params(char* type_specifier)
	{
		if(!strcmp(type_specifier, "void"))
		{
			printf("Parameters cannot be of type void\n");
			exit(0);
		}
		return 0;
	}

	char gettype(char *s, int flag)
	{
			for(int i = 0 ; i < 1001 ; i++ )
			{
				if(strcmp(ST[i].name,s)==0)
				{
					return ST[i].type[0];
				}
			}
		
	}

	void printST()
	{
		printf("%10s | %15s | %10s | %10s | %10s | %15s | %10s |\n","SYMBOL", "CLASS", "TYPE","VALUE", "LINE NO", "NESTING", "PARAMS COUNT");
		for(int i=0;i<100;i++) {
			printf("-");
		}
		printf("\n");
		for(int i = 0 ; i < 1001 ; i++)
		{
			if(ST[i].length == 0)
			{
				continue;
			}
			printf("%10s | %15s | %10s | %10s | %10d | %15d | %10d |\n",ST[i].name, ST[i].class, ST[i].type, ST[i].value, ST[i].lineno, ST[i].nestval, ST[i].params_count);
		}
    }


	void printCT()
	{
		printf("%10s | %15s\n","NAME", "TYPE");
		for(int i=0;i<81;i++) {
			printf("-");
		}
		printf("\n");
		for(int i = 0 ; i < 1001 ; i++)
		{
			if(CT[i].length == 0)
				continue;

			printf("%10s | %15s\n",CT[i].name, CT[i].type);
		}
	}
	char curid[20];
	char curtype[20];
	char curval[20];

#line 1195 "lex.yy.c"
#line 1196 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 450 "lex.l"

#line 1415 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 239 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 973 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 451 "lex.l"
{yylineno++;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 452 "lex.l"
{ }
	YY_BREAK
case 3:
/* rule 3 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 453 "lex.l"
{ } 
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 454 "lex.l"
{ }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 455 "lex.l"
{ }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 456 "lex.l"
;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 457 "lex.l"
{ return(';'); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 458 "lex.l"
{ return(','); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 459 "lex.l"
{ return('{'); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 460 "lex.l"
{ return('}'); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 461 "lex.l"
{ return('('); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 462 "lex.l"
{ return(')'); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 463 "lex.l"
{ return('['); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 464 "lex.l"
{ return(']'); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 465 "lex.l"
{ return(':'); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 466 "lex.l"
{ return('.'); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 468 "lex.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword"); return CHAR;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 469 "lex.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword"); return DOUBLE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 470 "lex.l"
{ insertSTline(yytext, yylineno); insertST(yytext, "Keyword"); return ELSE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 471 "lex.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword");return FLOAT;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 472 "lex.l"
{ insertST(yytext, "Keyword"); return WHILE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 473 "lex.l"
{ insertST(yytext, "Keyword"); return DO;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 474 "lex.l"
{ insertST(yytext, "Keyword"); return FOR;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 475 "lex.l"
{ insertST(yytext, "Keyword"); return IF;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 476 "lex.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword");return INT;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 477 "lex.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword");  return LONG;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 478 "lex.l"
{ insertST(yytext, "Keyword");  return RETURN;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 479 "lex.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword");  return SHORT;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 480 "lex.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword");  return SIGNED;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 481 "lex.l"
{ insertST(yytext, "Keyword");  return SIZEOF;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 482 "lex.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword");  return STRUCT;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 483 "lex.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword");  return UNION;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 484 "lex.l"
{ insertST(yytext, "Keyword");  return UNSIGNED;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 485 "lex.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword");  return VOID;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 486 "lex.l"
{ insertST(yytext, "Keyword");  return BREAK;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 487 "lex.l"
{ insertST(yytext, "Keyword");  return SWITCH;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 488 "lex.l"
{ insertST(yytext, "Keyword");  return CASE;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 489 "lex.l"
{ insertST(yytext, "Keyword");  return DEFAULT;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 490 "lex.l"
{ insertST(yytext, "Keyword");  return GOTO;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 491 "lex.l"
{ insertST(yytext, "Keyword");  return CONTINUE;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 492 "lex.l"
{ insertST(yytext, "Keyword");  return TYPEDEF;}	
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 493 "lex.l"
{ insertST(yytext, "Keyword");  return ENUM;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 494 "lex.l"
{ insertST(yytext, "Keyword");  return EXTERN;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 495 "lex.l"
{ insertST(yytext, "Keyword");  return CONST;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 496 "lex.l"
{ insertST(yytext, "Keyword");  return AUTO;}	
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 498 "lex.l"
{ return ELLIPSIS; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 499 "lex.l"
{return RIGHT_ASSIGN; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 500 "lex.l"
{return LEFT_ASSIGN; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 501 "lex.l"
{return RIGHT_OP; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 502 "lex.l"
{return LEFT_OP; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 503 "lex.l"
{ return INCREMENT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 504 "lex.l"
{ return DECREMENT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 505 "lex.l"
{ return LESS_THAN_EQ; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 506 "lex.l"
{ return LESS_THAN; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 507 "lex.l"
{ return GR_THAN_EQ; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 508 "lex.l"
{ return GR_THAN; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 509 "lex.l"
{ return EQ; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 510 "lex.l"
{ return NOT_EQ; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 511 "lex.l"
{ return AND; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 512 "lex.l"
{ return OR; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 513 "lex.l"
{ return XOR; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 514 "lex.l"
{ return MUL_ASSIGN; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 515 "lex.l"
{ return DIV_ASSIGN; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 516 "lex.l"
{ return MOD_ASSIGN; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 517 "lex.l"
{ return PLUS_ASSIGN; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 518 "lex.l"
{ return MINUS_ASSIGN; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 519 "lex.l"
{ return AND_ASSIGN; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 520 "lex.l"
{ return XOR_ASSIGN; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 521 "lex.l"
{ return OR_ASSIGN; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 522 "lex.l"
{ return AMP; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 523 "lex.l"
{ return EXC; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 524 "lex.l"
{ return TAB; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 525 "lex.l"
{ return MINUS; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 526 "lex.l"
{ return PLUS; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 527 "lex.l"
{ return MUL; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 528 "lex.l"
{ return DIV; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 529 "lex.l"
{ return MOD; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 530 "lex.l"
{ return PIPE; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 531 "lex.l"
{ return assignment_operator;}
	YY_BREAK
case 80:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 533 "lex.l"
{strcpy(curval,yytext); insertCT(yytext,"String Constant"); return string_constant;}
	YY_BREAK
case 81:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 534 "lex.l"
{strcpy(curval,yytext); insertCT(yytext,"Character Constant"); return character_constant;}
	YY_BREAK
case 82:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 535 "lex.l"
{strcpy(curid,yytext); insertST(yytext, "Array Identifier");  return IDENTIFIER;}
	YY_BREAK
case 83:
/* rule 83 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 536 "lex.l"
{strcpy(curval,yytext); insertCT(yytext, "Number Constant"); return integer_constant;}
	YY_BREAK
case 84:
/* rule 84 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 537 "lex.l"
{strcpy(curval,yytext); insertCT(yytext, "Floating Constant"); return float_constant;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 538 "lex.l"
{strcpy(curid,yytext);insertST(yytext,"Identifier");  return IDENTIFIER;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 540 "lex.l"
{
		if(yytext[0]=='#')
		{
			printf("Error in Pre-Processor directive at line no. %d\n",yylineno);
		}
		else if(yytext[0]=='/')
		{
			printf("ERR_UNMATCHED_COMMENT at line no. %d\n",yylineno);
		}
		else if(yytext[0]=='"')
		{
			printf("ERR_INCOMPLETE_STRING at line no. %d\n",yylineno);
		}
		else
		{
			printf("ERROR at line no. %d\n",yylineno);
		}
		printf("%s\n", yytext);
		return 0;
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 561 "lex.l"
ECHO;
	YY_BREAK
#line 1958 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 239 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 239 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 238);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 561 "lex.l"

